gocd-server:
  build: gocd-server/.
  ports:
   - "8153:8153"
  volumes:
   - ./mnt/var/lib/go-server:/var/lib/go-server
   - ./mnt/etc/go:/etc/go
   - ./mnt/var/log/go-server:/var/log/go-server
  environment:
   - AGENT_KEY=opensaasgocd
gocd-agent:
  build: gocd-agent/.
  links:
   - gocd-server
  environment:
   - AGENT_KEY=opensaasgocd
   - GO_SERVER=gocd-server
   - GO_SERVER_PORT=8153
gocd-agent-jdk8:
  build: gocd-agent-jdk8/.
  links:
   - gocd-server
  environment:
   - AGENT_KEY=opensaasgocd
   - AGENT_RESOURCES=java
   - GO_SERVER=gocd-server
   - GO_SERVER_PORT=8153
gocd-agent-nodejs:
  build: gocd-agent-nodejs/.
  links:
   - gocd-server
  environment:
   - AGENT_KEY=opensaasgocd
   - AGENT_RESOURCES=node
   - GO_SERVER=gocd-server
   - GO_SERVER_PORT=8153
gocd-agent-cloudfoundry:
  build: gocd-agent-cloudfoundry/.
  links:
   - gocd-server
  environment:
   - AGENT_KEY=opensaasgocd
   - AGENT_RESOURCES=cf
   - GO_SERVER=gocd-server
   - GO_SERVER_PORT=8153
